### ISSUE TITLE
Icons for changing modes not showing

### ISSUE THREAD

**Issue by pllgit** [nervetattoo/simple-thermostat#71]

**Comment by mmodestas** [comment]
I have the same issue..

**Comment by mmodestas** [comment]
Resolved with version 0.26

**Comment by alesoft73** [comment]
Many thanks, but ver.0.26 can't show in HACS....

**Comment by flinkebernt** [comment]
Can confirm that the modes are not showing in 0.25 and 0.26 is not available through HACS

**Comment by franzuu** [comment]
In HACS, after you choose this plugin, there is a "show beta" button in the hamburger menu in the top right. Then 0.26 becomes available. It didn't still work after installing 0.26.. Usin HA 0.97.

**Comment by Raoulex** [comment]
icons for changing modes still not showing, using HA 0.100.2
